# Pytorch Tutorial

* [강의 출처](https://www.youtube.com/watch?v=St7EhvnFi6c&list=PLQ28Nx3M4JrhkqBVIXg-i5_CVVoS1UzAv&index=3&t=46s)
* [강의 출처](https://www.youtube.com/watch?v=XkqdNaNQGx8&list=PLQ28Nx3M4JrhkqBVIXg-i5_CVVoS1UzAv&index=3)
* [코드 출처](https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-01_tensor_manipulation.ipynb)

# Summary

* if underbar, no returns, inplace operation

In [1]:
import torch
import numpy as np

## Make Tensor

In [2]:
t_1d = torch.FloatTensor([1,2,3,4])
t_2d = torch.Tensor([[1,2,4,3,],
                     [5,6,7,8]])

In [3]:
# shape
t_1d.shape, t_2d.shape

(torch.Size([4]), torch.Size([2, 4]))

In [4]:
# dim
t_1d.dim(), t_2d.dim()

(1, 2)

In [5]:
# slicing
print(t_1d[:-1])
print(t_2d[:,0])

tensor([1., 2., 3.])
tensor([1., 5.])


## Operation

In [6]:
# matmul
t_2d.matmul(t_1d)

tensor([29., 70.])

In [7]:
# mul
t_2d.mul(t_1d)

# same
t_2d * t_1d

tensor([[ 1.,  4., 12., 12.],
        [ 5., 12., 21., 32.]])

In [8]:
# mean
# numpy, axis = torch, dim
t_2d.mean(), t_2d.mean(dim=0), t_2d.mean(dim=1)

(tensor(4.5000),
 tensor([3.0000, 4.0000, 5.5000, 5.5000]),
 tensor([2.5000, 6.5000]))

In [9]:
# sum
# numpy, axis = torch, dim
t_2d.sum(), t_2d.sum(dim=0), t_2d.sum(dim=1)

(tensor(36.), tensor([ 6.,  8., 11., 11.]), tensor([10., 26.]))

In [10]:
# max, min
t_2d.max(dim=0), t_2d.max(dim=1) # return max, argmax

((tensor([5., 6., 7., 8.]), tensor([1, 1, 1, 1])),
 (tensor([4., 8.]), tensor([2, 3])))

### view

In [11]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])

t = torch.FloatTensor(t)
t, t.shape

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],
 
         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]), torch.Size([2, 2, 3]))

In [12]:
print(t.view(-1))
print(t.view(-1,3))

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


### squeeze

In [13]:
t = torch.FloatTensor([[0], [1], [2]])
t, t.shape

(tensor([[0.],
         [1.],
         [2.]]), torch.Size([3, 1]))

In [14]:
t.squeeze(), t.squeeze().shape

(tensor([0., 1., 2.]), torch.Size([3]))

### unsqueeze

In [15]:
t = torch.Tensor([0, 1, 2])
t, t.shape

(tensor([0., 1., 2.]), torch.Size([3]))

In [16]:
t.unsqueeze(1)

tensor([[0.],
        [1.],
        [2.]])

In [17]:
# same
t.unsqueeze(-1)
t.reshape(-1, 1)

tensor([[0.],
        [1.],
        [2.]])

### scatter

In [18]:
t = torch.LongTensor([[0], [1], [2], [0]])
t, t.shape

(tensor([[0],
         [1],
         [2],
         [0]]), torch.Size([4, 1]))

In [19]:
one_hot = torch.zeros(4, 3)
one_hot.scatter(dim=1, index=t, source=3)

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.],
        [3., 0., 0.]])

### type casting

In [20]:
t = torch.LongTensor([1, 2, 3, 4])
t, t.shape

(tensor([1, 2, 3, 4]), torch.Size([4]))

In [21]:
t.float()

tensor([1., 2., 3., 4.])

In [22]:
bt = torch.ByteTensor([True, False, False, True])
bt.dtype

torch.uint8

### Concatenation

In [23]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
x.shape, y.shape

(torch.Size([2, 2]), torch.Size([2, 2]))

In [24]:
torch.cat([x,y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [25]:
torch.cat([x,y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

### stacking

In [26]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [27]:
torch.stack([x, y, z], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [28]:
torch.stack([x, y, z], dim=1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

### ones and zeros like

In [29]:
x = torch.Tensor([[0, 1, 2], [2, 1, 0]])
x, x.shape

(tensor([[0., 1., 2.],
         [2., 1., 0.]]), torch.Size([2, 3]))

In [30]:
# same
torch.ones(x.shape)
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
# same
torch.zeros(x.shape)
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])