# Linear Regression

* [강의출처](https://www.youtube.com/watch?v=kyjBMuNM1DI&list=PLQ28Nx3M4JrhkqBVIXg-i5_CVVoS1UzAv&index=4)
* [코드출처](https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-02_linear_regression.ipynb)

## Summary

* basically, pytorch uses [NCHW](https://github.com/apache/incubator-mxnet/issues/5778) format

## Module

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## Data

In [2]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

## Weight and Bias

In [3]:
W = torch.zeros(x_train.shape[-1], requires_grad=True)
b = torch.zeros(x_train.shape[-1], requires_grad=True)

In [4]:
W,b

(tensor([0.], requires_grad=True), tensor([0.], requires_grad=True))

## Hypothesis

In [5]:
h = W * x_train + b
h

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)

## Cost

In [6]:
cost = torch.mean((h - y_train) ** 2)
cost

tensor(4.6667, grad_fn=<MeanBackward1>)

## Gradient 

In [7]:
opt = optim.SGD([W, b], lr=0.01)

In [8]:
opt.zero_grad()
cost.backward()
opt.step()

In [9]:
W, b

(tensor([0.0933], requires_grad=True), tensor([0.0400], requires_grad=True))

## Full code

In [10]:
# data load
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# initailize
W = torch.zeros(x_train.shape[-1], requires_grad=True)
b = torch.zeros(x_train.shape[-1], requires_grad=True)
opt = optim.SGD([W, b], lr=0.01)
nb_epochs = 1000

# train
for epoch in range(1, nb_epochs+1):
    
    # hypothesis
    h = x_train * W + b
    
    # cost
    c = ((h - y_train) ** 2).mean()
    
    # initialize gradient as 0
    opt.zero_grad()
    # calulate gradient
    c.backward()
    opt.step()
    
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), c.item()
        ))

Epoch  100/1000 W: 0.873, b: 0.290 Cost: 0.012101
Epoch  200/1000 W: 0.900, b: 0.228 Cost: 0.007478
Epoch  300/1000 W: 0.921, b: 0.179 Cost: 0.004621
Epoch  400/1000 W: 0.938, b: 0.141 Cost: 0.002855
Epoch  500/1000 W: 0.951, b: 0.111 Cost: 0.001764
Epoch  600/1000 W: 0.962, b: 0.087 Cost: 0.001090
Epoch  700/1000 W: 0.970, b: 0.068 Cost: 0.000674
Epoch  800/1000 W: 0.976, b: 0.054 Cost: 0.000416
Epoch  900/1000 W: 0.981, b: 0.042 Cost: 0.000257
Epoch 1000/1000 W: 0.985, b: 0.033 Cost: 0.000159


## Use Pytorch Method

In [11]:
# data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [12]:
# model
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)
        
    def forward(self, x):
        return self.linear(x)


model = LinearRegressionModel()

In [13]:
# optimizer
opt = optim.SGD(model.parameters(), lr = 0.01)

In [14]:
# constants
nb_epochs = 1000

In [15]:
for epoch in range(1, nb_epochs + 1):
    
    h = model(x_train)
    c = F.mse_loss(h, y_train)
    
    opt.zero_grad()
    c.backward()
    opt.step()
    
    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, c.item()
        ))

Epoch  100/1000 W: 0.880, b: 0.273 Cost: 0.010743
Epoch  200/1000 W: 0.906, b: 0.215 Cost: 0.006638
Epoch  300/1000 W: 0.926, b: 0.169 Cost: 0.004102
Epoch  400/1000 W: 0.942, b: 0.133 Cost: 0.002535
Epoch  500/1000 W: 0.954, b: 0.104 Cost: 0.001566
Epoch  600/1000 W: 0.964, b: 0.082 Cost: 0.000968
Epoch  700/1000 W: 0.972, b: 0.064 Cost: 0.000598
Epoch  800/1000 W: 0.978, b: 0.051 Cost: 0.000370
Epoch  900/1000 W: 0.982, b: 0.040 Cost: 0.000228
Epoch 1000/1000 W: 0.986, b: 0.031 Cost: 0.000141
