# Deep Neural Network (1)

* XOR 문제
* XOR 문제의 해결
* Convergence 0 문제

* [강의출처](https://www.youtube.com/watch?v=KofAX-K4dk4&list=PLQ28Nx3M4JrhkqBVIXg-i5_CVVoS1UzAv&index=12)
* [코드출처](https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-08_1_xor.ipynb)
* [코드출처](https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-08_2_xor_nn.ipynb)

## XOR Problem

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# for reproducibility
torch.manual_seed(42)
if device == 'cuda':
    torch.cuda.manual_seed_all(42)

In [3]:
# data
X = torch.FloatTensor([[0, 0], [0, 1], [1, 0], [1, 1]]).to(device)
Y = torch.FloatTensor([[0], [1], [1], [0]]).to(device)

In [8]:
# model
linear = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()

model = nn.Sequential(linear,
                      sigmoid).to(device)

In [10]:
# optimizer
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [12]:
nb_epochs = 10000

for epoch in range(1, nb_epochs+1):
    
    hypothesis = model(X)
    cost = F.binary_cross_entropy(hypothesis, Y)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(epoch, cost.item())

1000 0.6931471824645996
2000 0.6931471824645996
3000 0.6931471824645996
4000 0.6931471824645996
5000 0.6931471824645996
6000 0.6931471824645996
7000 0.6931471824645996
8000 0.6931471824645996
9000 0.6931471824645996
10000 0.6931471824645996


In [27]:
with torch.no_grad():
    hypothesis = model(X)
    prediction = (hypothesis > 0.5).float()
    accuracy = (prediction == Y).float().mean()
    
    print(accuracy.item(), '\n', hypothesis.numpy())

0.5 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Solve XOR Problem

In [55]:
# model
layer1 = nn.Linear(2, 2, bias=True)
layer2 = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()

model = nn.Sequential(layer1, 
                      sigmoid, 
                      layer2,
                      sigmoid).to(device)

In [56]:
# optimizer
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [57]:
nb_epochs = 10000

for epoch in range(1, nb_epochs+1):
    
    hypothesis = model(X)
    cost = F.binary_cross_entropy(hypothesis, Y)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(epoch, cost.item())

1000 0.6924803256988525
2000 0.6896904110908508
3000 0.6590722799301147
4000 0.4432142376899719
5000 0.16556179523468018
6000 0.0757618397474289
7000 0.04603925347328186
8000 0.032415106892585754
9000 0.024802055209875107
10000 0.0199970044195652


In [48]:
with torch.no_grad():
    hypothesis = model(X)
    prediction = (hypothesis > 0.5).float()
    accuracy = (prediction == Y).float().mean()
    
    print(accuracy.item(), '\n', (hypothesis.numpy() > 0.5) * 1)

1.0 
 [[0]
 [1]
 [1]
 [0]]


## Convergence 0 Promblem

In [59]:
# model
layer1 = nn.Linear(2, 2, bias=True)
layer2 = nn.Linear(2, 2, bias=True)
layer3 = nn.Linear(2, 2, bias=True)
layer4 = nn.Linear(2, 2, bias=True)
layer5 = nn.Linear(2, 2, bias=True)
layer6 = nn.Linear(2, 2, bias=True)
layer7 = nn.Linear(2, 2, bias=True)
layer8 = nn.Linear(2, 2, bias=True)
layer9 = nn.Linear(2, 2, bias=True)
layer10 = nn.Linear(2, 1, bias=True)
sigmoid = nn.Sigmoid()

model = nn.Sequential(layer1, 
                      sigmoid, 
                      layer2,
                      sigmoid,
                      layer3,
                      sigmoid,
                      layer4,
                      sigmoid,
                      layer5,
                      sigmoid,
                      layer6,
                      sigmoid,
                      layer7,
                      sigmoid,
                      layer8,
                      sigmoid,
                      layer9,
                      sigmoid,
                      layer10,
                      sigmoid).to(device)

In [60]:
# optimizer
optimizer = optim.SGD(model.parameters(), lr=0.1)

In [61]:
nb_epochs = 10000

for epoch in range(1, nb_epochs+1):
    
    hypothesis = model(X)
    cost = F.binary_cross_entropy(hypothesis, Y)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(epoch, cost.item())

1000 0.6931471824645996
2000 0.6931471824645996
3000 0.6931471824645996
4000 0.6931471824645996
5000 0.6931471824645996
6000 0.6931471824645996
7000 0.6931471824645996
8000 0.6931471824645996
9000 0.6931471824645996
10000 0.6931471824645996


In [66]:
with torch.no_grad():
    hypothesis = model(X)
    prediction = (hypothesis > 0.5).float()
    accuracy = (prediction == Y).float().mean()
    
    print(accuracy.item(), '\n', (hypothesis.numpy()))

0.5 
 [[0.5]
 [0.5]
 [0.5]
 [0.5]]
